-- Tablespace configuration for data, indexes, and temp
-- NOTE: Paths adjusted for Windows XE installation

-- Data tablespace
CREATE TABLESPACE data_ts
  DATAFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\MON_26973_AMOSNKURUNZIZA_HOSPITALMS_DB\data_ts01.dbf'
  SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- Index tablespace
CREATE TABLESPACE index_ts
  DATAFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\MON_26973_AMOSNKURUNZIZA_HOSPITALMS_DB\index_ts01.dbf'
  SIZE 100M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

-- Temporary tablespace
CREATE TEMPORARY TABLESPACE temp_ts
  TEMPFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\MON_26973_AMOSNKURUNZIZA_HOSPITALMS_DB\temp_ts01.dbf'
  SIZE 100M AUTOEXTEND ON NEXT 25M MAXSIZE UNLIMITED;
